// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_bots': 'enable',
    'aws_bots_config': [{"name":"ScheduleAppointment","alias":"$LATEST","description":"","bot-template":"bot-import","commands-help":[],"region":"us-west-2"}],
    'aws_cognito_identity_pool_id': 'us-west-2:0e7c96df-5d49-4a49-99d3-dbbb06f25829',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'client-hosting-mobilehub-1089888358',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd31gtkr526050z.cloudfront.net',
    'aws_mobile_analytics_app_id': 'f0b09a61cffd4e77a249bf265e7b2e4b',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '20900456-cee1-40f2-a9d5-86a8f63012d0',
    'aws_project_name': 'client-2020-05-03-18-16-19',
    'aws_project_region': 'us-west-2',
    'aws_resource_name_prefix': 'client-mobilehub-1089888358',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_B4iXIcHh4',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '6i4j508rft36bo272gsrfsmfls',
}

export default awsmobile;
