#!/bin/sh
    echo "Running deployment script"
    ssh ubuntu@172.31.17.206 << EOF
    pwd
    whoami 
    echo "after git pull code 2"
    cd ~/Project/ESP272/
    pwd
    echo "after git pull code 3"
    sudo git pull origin master
    echo "after git pull code 4"
    sudo npm install
    #sudo npm install -g nodemon pm2
    pm2 restart all
    exit
 
    EOF