#!/bin/sh

    ssh ubuntu@172.31.1.65 
    echo "after git pull code 2"
    cd ~/ESP272
    echo "after git pull code 3"
    sudo git pull origin master
    echo "after git pull code 4"
    sudo npm install
    #sudo npm install -g nodemon pm2
    sudo pm2 restart ecosystem.config.js
    exit